### ISSUE TITLE
key_words_train_features.df

### ISSUE THREAD

**Issue by dabaitudiu** [nlpjoe/daguan-classify-2018#3]
博主你好，请问在train_predict.py这个文件中
```python
def static_data_prepare():
    train_y = pd.read_csv(config.TRAIN_X, usecols=['label_c_numeric']).values
    kw_train_df = pd.read_csv('../data/feature/key_words_train_feature.df')
    kw_test_df = pd.read_csv('../data/feature/key_words_test_feature.df')
```
里面的**key_words_train_features.df**是怎么得来的？是过滤掉低频词之后直接save的df吗？

**Comment by nlpjoe** [comment]
不是，传统方法都可以。
这段代码我没用，不用管




    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            joezhow777
                            
                            
                                
                                    邮箱：joezhow777@gmail.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


On 02/16/2019 17:35, Li Zhenhan wrote: 博主你好，请问在train_predict.py这个文件中
def static_data_prepare():
    train_y = pd.read_csv(config.TRAIN_X, usecols=['label_c_numeric']).values
    kw_train_df = pd.read_csv('../data/feature/key_words_train_feature.df')
    kw_test_df = pd.read_csv('../data/feature/key_words_test_feature.df')
里面的key_words_train_features.df是怎么得来的？是过滤掉低频词之后直接save的df吗？

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nlpjoe/daguan-classify-2018","title":"nlpjoe/daguan-classify-2018","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/nlpjoe/daguan-classify-2018"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"key_words_train_features.df (#3)"}],"action":{"name":"View Issue","url":"https://github.com/nlpjoe/daguan-classify-2018/issues/3"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/nlpjoe/daguan-classify-2018/issues/3",
"url": "https://github.com/nlpjoe/daguan-classify-2018/issues/3",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dabaitudiu** [comment]
okok 谢谢博主
